### PR TITLE
fixed special characters

### PR DESCRIPTION
**Pull request by nim4**
fixing special characters in password([https://github.com/JeffHoogland/esudo/issues/2](https://github.com/JeffHoogland/esudo/issues/2))

### CODE REVIEW

**Comment by nim4** [comment]
first I converted there and it passes the authentication phase but it can not execute the command. my guess is if we change it inside password_check we have to change it again inside run_command as well

**Comment by kaihu** [comment]
See if this works:

Move password = en.entry from line 208 to beginning of password_check and convert it there, then change esudo_ok (lines 245 and 256) to use the password directly.

**Comment by rbtylee** [comment]
I have been looking at this issue with a known password  that breaks esudo, namely ľščťžýáíéúä. 

Your htmlparser fix is brilliant and probably fixes the issue with certain passwords but alas in my tests fails to fix it with my test case  above :(

**Comment by rbtylee** [comment]
Ok a fix for my password test case (ľščťžýáíéúä) is to add at line 208:

` password = en.entry.encode('utf8')`

and then again at line 257 

Now this still fails for passwords that contain html or markup code like password = '&gt;' but we can also incorporate nim4's fix or perhaps use elms markup_to_utf8 function. Doing so should result in esudo accepting all passwords  that I personally know to fail.

...@kaihu if you think it would be better to 'Move password = en.entry from line 208 to beginning of password_check and convert it there, then change esudo_ok (lines 245 and 256) to use the password directly.' Do what ever you think is best.

**Comment by rbtylee** [comment]
**@kaihu**,  elms markup_to_utf8 function doesn't work as expected. For my test case 

`password = "ľščťžýáíéúä"`

`password = elementary.markup_to_utf8(en.entry.encode('utf8'))`

Fails and yields:

`password = u'\u013e\u0161\u010d\u0165\u017e\xfd\xe1\xed\xe9\xfa\xe4'`

Whereas 

`password = HTMLParser().unescape(en.entry.encode('utf8'))`

Succeeds and yields

`password = '\xc4\xbe\xc5\xa1\xc4\x8d\xc5\xa5\xc5\xbe\xc3\xbd\xc3\xa1\xc3\xad\xc3\xa9\xc3\xba\xc3\xa4'`

**@nim4**, I recently was added to the collaborators for esudo and as your latest commit is nonfunctional and rather messed up I am going to reject this request. But certainly I thank you for the suggestion of using HTMLParser() to strip HTML/XML code from the password entered :) My commit, 2b74f59, addresses this issue and works for all cases of broken passwords I know about and utilizes the HTMLParser function.

**Pull request closed without merging**
